<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>amist.AMISTReader</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <!--
      Enables trim analyzers and full trimming during Release mode.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
    <TrimMode>full</TrimMode>
    <AndroidSigningKeyStore></AndroidSigningKeyStore>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <PublishTrimmed>True</PublishTrimmed>
    <RunAOTCompilation>True</RunAOTCompilation>
    <Optimize>True</Optimize>
    <AndroidKeyStore>False</AndroidKeyStore>
    <AndroidSigningKeyAlias></AndroidSigningKeyAlias>
    <AndroidSigningKeyPass></AndroidSigningKeyPass>
    <AndroidSigningStorePass></AndroidSigningStorePass>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AndroidKeyStore>False</AndroidKeyStore>
    <AndroidSigningKeyAlias></AndroidSigningKeyAlias>
    <AndroidSigningKeyPass></AndroidSigningKeyPass>
    <AndroidSigningStorePass></AndroidSigningStorePass>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CodeHollow.FeedReader" Version="1.2.6" />
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.7.1.1" />
    <PackageReference Include="Xamarin.AndroidX.SwipeRefreshLayout" Version="1.2.0" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.13.0" />
  </ItemGroup>
</Project>